### ISSUE TITLE
Segfaults when keep running step commands

### ISSUE THREAD

**Issue by honggyukim** [cgdb/cgdb#114]
I see a segfault when I keep running `step` command for a simple hello world program. The problematic commit seems to be 6694a8a.
Please see the log below:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000413b06 in highlight_node (node=0xffffffffffffffff) at sources.cpp:416
416                         sbpush(buf->lines[line].attrs, line_attr);
(gdb) bt
#0  0x0000000000413b06 in highlight_node (node=0xffffffffffffffff) at sources.cpp:416
#1  0x656c626d65737361 in ?? ()
#2  0x662065646f632072 in ?? ()
#3  0x74636e756620726f in ?? ()
#4  0x6c727473206e6f69 in ?? ()
#5  0x00226e00003a6e65 in ?? ()
#6  0x6e45223d7264686c in ?? ()
#7  0x0000000000000041 in ?? ()
#8  0x000000200000002f in ?? ()
#9  0x0000000000000000 in ?? ()
(gdb) p buf
$1 = (buffer *) 0x67676e6f682f656d
(gdb) p buf->lines
Cannot access memory at address 0x67676e6f682f656d
(gdb) p line
$2 = -1
```

**Comment by honggyukim** [comment]
In addition to this, I also see some double-free error and many other segfaults from the recent changes. The gdb log was generated based on the commit 6694a8a but the current master so the line number may be different from the master.

**Comment by mikesart** [comment]
There were fixes in 2ec70f2 and 0095262. Are you building and running with those commits?

**Comment by mikesart** [comment]
I was able to repro this in an Ubuntu Trusty container with gdb 7.71 and the latest cgdb source code. I was also able to reproduce this running the latest Debian Stretch with gdb 7.12 by doing ":set disasm" and stepping. Several things appear to be broken with disassembly mode as it stopped following the current location before it crashed.

```
(gdb) bt
#0  0x00007fcee6212c37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fcee6216028 in __GI_abort () at abort.c:89
#2  0x00007fcee624f2a4 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7fcee635d6b0 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007fcee625b55e in malloc_printerr (ptr=<optimized out>, str=0x7fcee635d798 "double free or corruption (!prev)", action=1) at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=1) at malloc.c:3840
#5  0x00007fcee625d780 in _int_realloc (av=0x7fcee659a760 <main_arena>, oldp=0x2264e40, oldsize=1552, nb=1704623008) at malloc.c:4340
#6  0x00007fcee625eed9 in __GI___libc_realloc (oldmem=0x2264e50, bytes=1704622992) at malloc.c:3029
#7  0x0000000000426f59 in cgdb_realloc (ptr=<optimized out>, size=<optimized out>) at sys_util.cpp:54
#8  0x000000000042728a in stb__sbgrowf (arr=arr@entry=0x206aa88, increment=increment@entry=1, itemsize=itemsize@entry=8) at sys_util.cpp:209
#9  0x00000000004135d7 in gdbwire_stream_record_callback (context=0x206aa70, stream_record=<optimized out>) at commands.cpp:358
#10 0x0000000000414b82 in gdbwire_mi_output_callback (context=0x206ac00, output=0x225fcb0) at gdbwire.c:7530
#11 0x0000000000418c0e in gdbwire_mi_parser_parse_line (line=0x2262a70 "~\"Dump of assembler code for function strlen:\\n\"\n", parser=0x206ab40)
    at gdbwire.c:1754
#12 gdbwire_mi_parser_push_data (parser=0x206ab40, data=<optimized out>, size=<optimized out>) at gdbwire.c:1874
#13 0x000000000041285f in tgdb_process (tgdb=0x20682c0, buf=buf@entry=0x7ffd0cf7d5d0 "", n=n@entry=4096, is_finished=is_finished@entry=0x7ffd0cf7d5c4)
    at tgdb.cpp:1076
#14 0x000000000040624f in gdb_input () at cgdb.cpp:1181
#15 0x0000000000404d79 in main_loop () at cgdb.cpp:1506
#16 main (argc=<optimized out>, argv=<optimized out>) at cgdb.cpp:1844
```

**Comment by honggyukim** [comment]
@brasko Sorry for not answering a while. It works fine now. Thanks!
